spring:
  application:
    name: ToDo

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${PORT}

jwt:
  access_token_expiration: ${ACCESS_TOKEN_EXP}
  refresh_token_expiration: ${REFRESH_TOKEN_EXP}
  secret: ${JWT_SECRET}

frontend_url : ${FRONTEND_URL}

